# Generated by Django 5.2.17 on 2026-10-03 14:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=api.models.generate_project_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=350)),
                ('description', models.TextField(blank=True, default='')),
                ('roles_needed', models.JSONField(blank=True, default=list)),
                ('github', models.CharField(blank=True, default='', max_length=255)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'techstack',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='Full-Stack Developer', max_length=255)),
                ('bio', models.TextField(blank=True, default='Passionate developer building collaborative tools.')),
                ('location', models.CharField(blank=True, default='Bengaluru, India', max_length=150)),
                ('github_url', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='api.user')),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='api.user'),
        ),
        migrations.CreateModel(
            name='ProjectTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='tech_associations', to='api.project')),
                ('tech', models.ForeignKey(db_column='tech_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_associations', to='api.techstack')),
            ],
            options={
                'db_table': 'project_ts',
                'unique_together': {('project', 'tech')},
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Contributor', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to='api.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.user')),
            ],
            options={
                'db_table': 'contributers',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='connected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='connections_initiated', to='api.user')),
                ('user2', models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to='api.user')),
            ],
            options={
                'db_table': 'connections',
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
