# Generated by Django 5.2.17 on 2026-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
