# Generated by Django 5.2.17 on 2026-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
