# Generated by Django 5.2.17 on 2026-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
