# Generated by Django 5.2.18 on 2026-10-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connection_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forked_from',
            field=models.ForeignKey(blank=True, db_column='forked_from_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks_created', to='api.project'),
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked_projects', to='api.user')),
            ],
            options={
                'db_table': 'project_likes',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
